### ISSUE TITLE
Controlling single-strung vs double-strung courses?

### ISSUE THREAD

**Issue by chrisspen** [Laukku/lutedesigner#6]
Fantastic job on this tool. It's quite remarkable.

Question about stringing. Is there any way to configure a design to use single-strung vs double-strung courses?

I'd like to design a swan-neck archlute that is either single-strung, or is just double strung for the fretted courses, and uses single strings for all the unfretted courses. I don't like playing with double-strung courses, plus reducing the peg count will drastically shorten the size of the peg boxes.

It looks like the default assumes all courses are double-strung except for the chanterelle. Is that hard-coded or is there a way to change that?

**Comment by Laukku** [comment]
Check the "All Singles" checkbox to the right of each string length group under "Strings". It may be hidden if your resolution or window is too narrow, but in that case there should be a horizontal scrollbar in that container.

**Comment by chrisspen** [comment]
Interesting, thanks. I see the option, and it works. Although I notice it keeps the pegbox the same size with the same number of peg holes regardless of the checkbox option. I guess there's no way to shorten the pegboxes?

**Comment by Laukku** [comment]
The swan neck shape is currently hard coded.

**Comment by chrisspen** [comment]
I see. Thanks.
